version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - /docker-entrypoint-initdb
      - ./data:/var/lib/mysql
      - './mysql/conf/my.cnf:/etc/my.cnf'
    restart: always
    networks:
      - node_network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 80s docker-entrypoint.sh
    depends_on:
      - mysql
    environment:
      - 'port=3000'
    ports:
      - '3000:3000'
    command:
      - 'node'
      - 'index.js'
    networks:
      - node_network
  nginx:
    depends_on:
      - node
    build:
      context: ./nginx
    ports:
      - '8080:80'
    networks:
      - node_network
networks:
  node_network:
    driver: bridge
